// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "softek",
    "version": "1"
  },
  "paths": {
    "/swapi/people/findAll": {
      "get": {
        "summary": "findAll",
        "description": "",
        "operationId": "findAll.get.swapi/people/findAll",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/people/findOne/{id}": {
      "get": {
        "summary": "findById",
        "description": "",
        "operationId": "findById.get.swapi/people/findOne/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/planets/findOnePlanet/{id}": {
      "get": {
        "summary": "findOnePlanet",
        "description": "",
        "operationId": "findOnePlanet.get.swapi/planets/findOnePlanet/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi/planets/findPlanets": {
      "get": {
        "summary": "findPlanets",
        "description": "",
        "operationId": "findPlanets.get.swapi/planets/findPlanets",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/users/create": {
      "post": {
        "summary": "create",
        "description": "",
        "operationId": "create.post.users/create",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};